@startuml Data Structure
title IBMTEST3 Data Structure

class "WORKING-STORAGE" {
  +SAVE-EQUIP-INIT-NBR: X(10)
  +SAVE-RECLAIM-CODE: XX
  +SAVE-TRIP-CONTROL-NBR: 9(09)
}

class "GL101-GENERAL-GLOSSARY" {
  +GL101-SWITCH-VALUES
  +GL101-INDICATOR-VALUES
  +GL101-SCREEN-STATUS
  +GL101-LOGICAL-VIEWS
}

class "GL101-SWITCH-VALUES" {
  +GL101-YES: X(01) = 'Y'
  +GL101-NO: X(01) = 'N'
}

class "GL101-INDICATOR-VALUES" {
  +GL101-INDIC-ON: 1 = B'1'
  +GL101-INDIC-OFF: 1 = B'0'
}

class "GL101-SCREEN-STATUS" {
  +GL101-SS-F3: X(03) = 'F3 '
  +GL101-SS-F12: X(03) = 'F12'
}

class "GL101-LOGICAL-VIEWS" {
  +GL101-LV-L01: X(03) = 'L01'
  +GL101-LV-L02: X(03) = 'L02'
  +GL101-LV-L03: X(03) = 'L03'
  +GL101-LV-L04: X(03) = 'L04'
}

class "GL102-DBIO-GLOSSARY" {
  +GL102-IO-COMMANDS
  +GL102-FILE-STATUS
  +GL102-RETURN-STATUS
  +GL102-SWITCH-VALUES
}

class "GL102-IO-COMMANDS" {
  +GL102-IO-READ: X(03) = 'R  '
  +GL102-IO-READ-1ST: X(03) = 'RF '
  +GL102-IO-READ-LAST: X(03) = 'RL '
  +GL102-IO-READ-NEXT: X(03) = 'RN '
  +GL102-IO-READ-PREV: X(03) = 'RP '
  +GL102-IO-ADD: X(03) = 'A  '
  +GL102-IO-UPDATE: X(03) = 'U  '
  +GL102-IO-DELETE: X(03) = 'D  '
  +GL102-IO-OPEN-IO: X(03) = 'OIO'
  +GL102-IO-OPEN-INPUT: X(03) = 'OI '
  +GL102-IO-CLOSE: X(03) = 'C  '
  +GL102-IO-READ-SERIES: X(03) = 'RS '
  +GL102-IO-READ-LOCKED: X(03) = 'RK '
  +GL102-IO-READ-NEXT-LOCKED: X(03) = 'RNK'
}

"WORKING-STORAGE" --> "GL101-GENERAL-GLOSSARY"
"WORKING-STORAGE" --> "GL102-DBIO-GLOSSARY"
"GL101-GENERAL-GLOSSARY" --> "GL101-SWITCH-VALUES"
"GL101-GENERAL-GLOSSARY" --> "GL101-INDICATOR-VALUES"
"GL101-GENERAL-GLOSSARY" --> "GL101-SCREEN-STATUS"
"GL101-GENERAL-GLOSSARY" --> "GL101-LOGICAL-VIEWS"
"GL102-DBIO-GLOSSARY" --> "GL102-IO-COMMANDS"
@enduml
